# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
          cache: 'pnpm'
      - run: pnpm i --frozen-lockfile
      - run: pnpm run --if-present build
      - run: pnpm run --if-present test
      - run: pnpm run ci
      - run: |
          . ./scripts/get-npm-tag.sh
          cd "packages/$(cat .packagename)"

          VERSION=$(node -p "require('./package.json').version")
          echo "Package version: $VERSION"
          TAG=$(get_npm_tag "$VERSION")
          if [ $? -ne 0 ]; then
            echo "Failed to get valid npm tag: $TAG"
            exit 1
          fi
          echo "Publishing with tag: $TAG"
          
          pnpm publish --ignore-scripts --no-git-checks --tag "$TAG"
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
